# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15669b5c3c80cc3daf9a83e9715111396ae04ab4514114264b44c9ced2cffadeea3dd748d7f621a508a859c5d89b71f49314aa6e4482b0e20abc2d699647d07d

test:
  secret_key_base: 5372736dfd8fcb9dbce0d81aa07ea7dc0588a0ed28d0cda388aa23b8f05ec213f949715def3dc2c6a8c0c82ce0312ad6871ae82568338ce67e1439efc2b8549d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
